import requests

api_key = ""
url = f"https://api.jotform.com/form?apiKey={api_key}"

payload = {
    "questions[0][type]": "control_head",
    "questions[0][text]": "Form Title",
    "questions[0][order]": "1",
    "questions[1][type]": "control_radio",
    "questions[1][calcValues]": "0|1|2|3|4",
    "questions[1][order]": "2",
    "questions[1][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[1][text]": "How often do you find yourself being overly critical of yourself?",
    "questions[1][spreadCols]": "5",
    "questions[2][type]": "control_radio",
    "questions[2][calcValues]": "0|1|2|3|4",
    "questions[2][order]": "3",
    "questions[2][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[2][text]": "How often do you judge others for their mistakes or shortcomings?",
    "questions[2][spreadCols]": "5",
    "questions[3][type]": "control_radio",
    "questions[3][calcValues]": "0|1|2|3|4",
    "questions[3][order]": "4",
    "questions[3][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[3][text]": "How often do you criticize circumstances or complain about your life?",
    "questions[3][spreadCols]": "5",
    "questions[4][type]": "control_radio",
    "questions[4][calcValues]": "0|1|2|3|4",
    "questions[4][order]": "5",
    "questions[4][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[4][text]": "How frequently do you feel the need to control or micromanage others?",
    "questions[4][spreadCols]": "5",
    "questions[5][type]": "control_radio",
    "questions[5][calcValues]": "0|1|2|3|4",
    "questions[5][order]": "6",
    "questions[5][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[5][text]": "How often do you get anxious when things don’t go according to your plan?",
    "questions[5][spreadCols]": "5",
    "questions[6][type]": "control_radio",
    "questions[6][calcValues]": "0|1|2|3|4",
    "questions[6][order]": "7",
    "questions[6][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[6][text]": "How frequently do you feel stressed about deadlines or deliverables?",
    "questions[6][spreadCols]": "5",
    "questions[7][type]": "control_radio",
    "questions[7][calcValues]": "0|1|2|3|4",
    "questions[7][order]": "8",
    "questions[7][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[7][text]": "How often do you strive for perfection and get upset when things aren’t perfect?",
    "questions[7][spreadCols]": "5",
    "questions[8][type]": "control_radio",
    "questions[8][calcValues]": "0|1|2|3|4",
    "questions[8][order]": "9",
    "questions[8][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[8][text]": "How frequently do you set extremely high standards for yourself and others?",
    "questions[8][spreadCols]": "5",
    "questions[9][type]": "control_radio",
    "questions[9][calcValues]": "0|1|2|3|4",
    "questions[9][order]": "10",
    "questions[9][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[9][text]": "How often do you feel irritated when others don’t meet your expectations?",
    "questions[9][spreadCols]": "5",
    "questions[10][type]": "control_radio",
    "questions[10][calcValues]": "0|1|2|3|4",
    "questions[10][order]": "11",
    "questions[10][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[10][text]": "How often do you feel compelled to please others, even at your own expense?",
    "questions[10][spreadCols]": "5",
    "questions[11][type]": "control_radio",
    "questions[11][calcValues]": "0|1|2|3|4",
    "questions[11][order]": "12",
    "questions[11][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[11][text]": "How frequently do you avoid conflict to keep others happy?",
    "questions[11][spreadCols]": "5",
    "questions[12][type]": "control_radio",
    "questions[12][calcValues]": "0|1|2|3|4",
    "questions[12][order]": "13",
    "questions[12][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[12][text]": "How often do you seek approval from others to feel valued?",
    "questions[12][spreadCols]": "5",
    "questions[13][type]": "control_radio",
    "questions[13][calcValues]": "0|1|2|3|4",
    "questions[13][order]": "14",
    "questions[13][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[13][text]": "How often do you find it difficult to stay focused on one task without getting bored?",
    "questions[13][spreadCols]": "5",
    "questions[14][type]": "control_radio",
    "questions[14][calcValues]": "0|1|2|3|4",
    "questions[14][order]": "15",
    "questions[14][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[14][text]": "How frequently do you jump from one activity to another without completing them?",
    "questions[14][spreadCols]": "5",
    "questions[15][type]": "control_radio",
    "questions[15][calcValues]": "0|1|2|3|4",
    "questions[15][order]": "16",
    "questions[15][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[15][text]": "How often do you feel uneasy or restless when things are too calm?",
    "questions[15][spreadCols]": "5",
    "questions[16][type]": "control_radio",
    "questions[16][calcValues]": "0|1|2|3|4",
    "questions[16][order]": "17",
    "questions[16][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[16][text]": "How often do you tie your self-worth to your accomplishments?",
    "questions[16][spreadCols]": "5",
    "questions[17][type]": "control_radio",
    "questions[17][calcValues]": "0|1|2|3|4",
    "questions[17][order]": "18",
    "questions[17][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[17][text]": "How frequently do you feel that you must be the best at everything you do?",
    "questions[17][spreadCols]": "5",
    "questions[18][type]": "control_radio",
    "questions[18][calcValues]": "0|1|2|3|4",
    "questions[18][order]": "19",
    "questions[18][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[18][text]": "How often do you push yourself beyond your limits to achieve more?",
    "questions[18][spreadCols]": "5",
    "questions[19][type]": "control_radio",
    "questions[19][calcValues]": "0|1|2|3|4",
    "questions[19][order]": "20",
    "questions[19][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[19][text]": "How often do you feel like life is unfair and that you are treated unjustly?",
    "questions[19][spreadCols]": "5",
    "questions[20][type]": "control_radio",
    "questions[20][calcValues]": "0|1|2|3|4",
    "questions[20][order]": "21",
    "questions[20][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[20][text]": "How frequently do you dwell on your problems and feel sorry for yourself?",
    "questions[20][spreadCols]": "5",
    "questions[21][type]": "control_radio",
    "questions[21][calcValues]": "0|1|2|3|4",
    "questions[21][order]": "22",
    "questions[21][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[21][text]": "How often do you seek sympathy or attention for your difficulties?",
    "questions[21][spreadCols]": "5",
    "questions[22][type]": "control_radio",
    "questions[22][calcValues]": "0|1|2|3|4",
    "questions[22][order]": "23",
    "questions[22][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[22][text]": "How often do you prioritize logic and reason over feelings and emotions?",
    "questions[22][spreadCols]": "5",
    "questions[23][type]": "control_radio",
    "questions[23][calcValues]": "0|1|2|3|4",
    "questions[23][order]": "24",
    "questions[23][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[23][text]": "How frequently do you find it difficult to empathize with others?",
    "questions[23][spreadCols]": "5",
    "questions[24][type]": "control_radio",
    "questions[24][calcValues]": "0|1|2|3|4",
    "questions[24][order]": "25",
    "questions[24][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[24][text]": "How often do you dismiss emotions as irrelevant in decision-making?",
    "questions[24][spreadCols]": "5",
    "questions[25][type]": "control_radio",
    "questions[25][calcValues]": "0|1|2|3|4",
    "questions[25][order]": "26",
    "questions[25][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[25][text]": "How often do you feel constantly on edge, anticipating problems?",
    "questions[25][spreadCols]": "5",
    "questions[26][type]": "control_radio",
    "questions[26][calcValues]": "0|1|2|3|4",
    "questions[26][order]": "27",
    "questions[26][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[26][text]": "How frequently do you worry about what could go wrong in any situation?",
    "questions[26][spreadCols]": "5",
    "questions[27][type]": "control_radio",
    "questions[27][calcValues]": "0|1|2|3|4",
    "questions[27][order]": "28",
    "questions[27][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[27][text]": "How often do you feel the need to stay alert and cautious at all times?",
    "questions[27][spreadCols]": "5",
    "questions[28][type]": "control_radio",
    "questions[28][calcValues]": "0|1|2|3|4",
    "questions[28][order]": "29",
    "questions[28][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[28][text]": "How often do you avoid difficult conversations or unpleasant tasks?",
    "questions[28][spreadCols]": "5",
    "questions[29][type]": "control_radio",
    "questions[29][calcValues]": "0|1|2|3|4",
    "questions[29][order]": "30",
    "questions[29][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[29][text]": "How frequently do you procrastinate on tasks that you don’t enjoy?",
    "questions[29][spreadCols]": "5",
    "questions[30][type]": "control_radio",
    "questions[30][calcValues]": "0|1|2|3|4",
    "questions[30][order]": "31",
    "questions[30][options]": "Never|Rarely|Sometimes|Often|Always",
    "questions[30][text]": "How often do you focus on the positive and ignore the negative aspects of situations?",
    "questions[30][spreadCols]": "5",
}
files = []
headers = {"Cookie": ""}
response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)
